### ISSUE TITLE
citation error

### ISSUE THREAD

**Issue by jaktk** [Global-Health-Engineering/bcsa#9]
Hi @larnsce, hi @salonivijay , by going through your package and looking for inspirations for hardware design, I think I've found this error in citation on the github page (what the package does):

```
#> To cite package 'bcsa' in publications use:
#> 
#>   Vijay S, Chilunga H, Khonje L, Kamjombo J, Tilley E, Schöbitz L
#>   (2024). "bcsa: What the Package Does (One Line, Title Case)."
```

**Comment by larnsce** [comment]
Thanks, @jaktk! I will sort that out
